package com.github.ninz9.ideaplugin.utils.exeptions

enum class ErrorType {
    INVALID_TOKEN,
    RATE_LIMIT_ERROR,
    SERVER_ERROR,
    OVERLOADED_ERROR,
    EMPTY_MESSAGE,
    REQUEST_TOO_LARGE,
    INSUFFICIENT_QUOTA,
    SERVICE_UNAVAILABLE,
    PERMISSION_DENIED,
    UNKNOWN_ERROR,
    TIMEOUT_ERROR,
}